### ISSUE TITLE
Windows not working but android works, in the same network

### ISSUE THREAD

**Issue by Yiyiyimu** [geph-official/geph2#26]
Windows version just keep loading for more than half an hour.

And why should we subscribe and type in credit card information only when we use the vpn which could cause information leak?

**Comment by nullchinchilla** [comment]
I'm not exactly sure why this would happen. Can you attach the logs you see at Settings > Debug logs? You'll have to switch on Geph to see the logs.

Information leakage due to typing in credit card info with Geph on is minimal, since there are only 4 Geph exits. We have to do it this way because geph.io is blocked in China, and thus you can't charge your account with Geph off.
